.azure-pipelines/ci.yml
.azure-pipelines/deploy.yml
CHANGES/24.removal
README.rst
docs/index.rst
setup.py
tox.ini

aiohttp 4.0 has dropped support for 3.5, so we can do so too.
Since we only ever released a 1.0.0a this shouldn't cause support issues.

Drop Python 3.5 support.

---

CHANGES/250.bugfix
setup.py

Prevent C sources (`_frozenlist.c`) from being included in binary distributions such as wheels, without affecting Cython sources (`_frozenlist.pyx`) or source distributions.
Adds
```python
exclude_package_data={"": [".c"]},
```
to `setup(…)` in `setup.py`.
Nothing changes except that the binary wheels are smaller because they do not contain `_frozenlist.c`.
https://github.com/aio-libs/frozenlist/issues/250
* The format is &lt;Name&gt; &lt;Surname&gt;.
* Please keep the list in alphabetical order, the file is sorted by name. 
* **This contribution is trivial, so this doesn’t seem necessary, but I can add it if  desired.**
* name it `<issue_id>.<type>` for example (588.bugfix)
* if you don't have an `issue_id` change it to the pr id after creating the pr
* ensure type is one of the …

Do not install C sources with binary distributions

---

.github/workflows/ci.yml
CHANGES/327.misc

We were missing `always()`, and use the alls-green action to verify the status of the test matrix jobs. Without `always()` the check step was being skipped whenever a test failed. :facepalm:
Fixes #327

CI: detect test matrix failure correctly

---

.github/workflows/ci.yml

Otherwise, towncrier exits with an exception when the current version has already been listed.

CI: use a fictional version when running towncrier

---

.pre-commit-config.yaml

I already introduced myself to aio-libs in https://github.com/aio-libs/pytest-aiohttp/pull/48, so I'm just doing more of the same here.
As in that case, I don't know if the `ci.skip` config is still needed, but I'm not suggesting removing it because there isn't enough evidence to make me confident that it isn't there on purpose.

Update check-jsonschema URL and version to latest

---

.github/workflows/ci.yml

GH actions moved to Ubuntu 22.04, so update to use libenchant-2-dev.

ci: use libenchant-2-dev

---

CHANGES/411.bugfix
frozenlist/__init__.py

The Tuple type hint is only used in a comment and can safely be removed.

Remove unused typing.Tuple import

---

.readthedocs.yml

The python.version option is considered legacy; use the new build.os and build.tools.python options to make sure we can build the docs correctly (sphinx 6.x needs Python 3.8 or newer).

ci: Update RTD configuration

---

.github/workflows/ci.yml
CHANGES/433.misc
requirements/ci.txt
tox.ini

This release is compatible with Python 3.12a05 (and up).  While here, extend
the tox configuration to also cover 3.11 and 3.12, and have GitHub test against
3.12.
Fixes #433

Upgrade cython to 3.0.0b1, add 3.12 to test matrix

---

docs/conf.py

Make it clearer why we ignore an import error for the spelling extension.

docs: remove unused imports from sphinx config

---

Makefile
docs/conf.py
docs/index.rst

While editing the conf.py file, clean up line lengths as well, and shut pyright up about the sphinxcontrib.spelling import.
Fixes #295

docs: validate docs more strictly, fix references

---

pytest.ci.ini
pytest.ini

These warnings otherwise would abort the test suite. See pytest-dev/pytest#10977.

Ignore depr warnings inside pytest on 3.12

---

.github/workflows/ci-cd.yml
CHANGES/553.feature
setup.cfg
tox.ini

Hello,
I believe it would be nice to have explicit support for Python 3.12.
So I'd like to propose this PR.
* enable testing for Python 3.12 and PyPy 3.8-3.10
* update `classifiers` at `setup.cfg`
No.
I suppose #541 might be resolved by releasing a new version once this PR is merged.
Since `cibuildwheel` was already updated to `2.16.2`, it will build `wheels` for Python 3.12 as well as for prior versions.
* name it `<issue_id>.<type>` for example (588.bugfix)
* if you don't have an `issue_id` change it to the pr id after creating the pr
* ensure type is one of the following:
* `.feature`: Signifying a new feature.
* `.bugfix`: Signifying a bug fix.
* `.doc`: Signifying a documentation improvement.
* `.removal`: Signifying a deprecation or removal of public API.
* `.misc`: A ticket has …

Ensure support for Python 3.12 and PyPy 3.8-3.10

---

.codecov.yml
CHANGES/567.bugfix.rst
CHANGES/571.bugfix.rst
frozenlist/__init__.py
frozenlist/_frozenlist.pyx
tests/test_frozenlist.py

This patch also increases the coverage level expectations in the Codecov config and adds a test that hits the line with the missing coverage.
Fixes #567

🐛 Fix `__class_getitem__` signature in classes

---

CHANGES/574.doc.rst
CHANGES/README.rst

These changes fix a broken link to `towncrier`'s philosophy.
Link from [Contributing docs](https://frozenlist.aio-libs.org/en/latest/contributing/guidelines/#adding-change-notes-with-your-prs) to `towncrier`'s philosophy will be fixed.
`N/A`

Fix the Towncrier philosophy link

---

CHANGES/573.doc.rst
CHANGES/573.packaging.rst
docs/spelling_wordlist.txt
packaging/pep517_backend/_backend.py
packaging/pep517_backend/_transformers.py

Hello @webknjaz,
I hope you can help to fix this.
Due to an issue with the configuration, links in the documentation [currently point](https://pypi.org/project/frozenlist/1.4.1/#packaging-updates-and-notes-for-downstreams) to `yarl`'s repo instead of `frozenslist`'s repo. To fix that, `yarl` substrings must be replaced with `frozenlist`.
Links to issues/PRs/commits will be fixed.
PR that introduces an issue:
* #560

Fix misleading URLs in the documentation

---

.github/workflows/ci-cd.yml

This timeout was hit a few times during yarl releases once we added Python 3.13 and its likely to make the next release fail here as well so lets avoid that.
We also need to do a release to make Python 3.13 wheels https://github.com/aio-libs/frozenlist/issues/608

Increase release timeout

---

CHANGES.rst
CHANGES/567.bugfix.rst
CHANGES/571.bugfix.rst
CHANGES/573.doc.rst
CHANGES/573.packaging.rst
CHANGES/574.doc.rst
CHANGES/595.packaging.rst
frozenlist/__init__.py

Release 1.5.0

---

.github/actions/cache-keys/action.yml
.github/actions/cache-pip-deps/action.yml
.github/workflows/ci-cd.yml
.github/workflows/reusable-linters.yml
.pre-commit-config.yaml
CHANGES/622.contrib.rst
MANIFEST.in

This is an experimental attempt to work around the bug in `actions/setup-python@v5` [[1]].
[1]: https://github.com/actions/setup-python/issues/1034

🧪 Drop `setup-python` cache from the test job

---

.github/workflows/reusable-linters.yml
.mypy.ini
.pre-commit-config.yaml
packaging/pep517_backend/_backend.py
packaging/pep517_backend/_compat.py
packaging/pep517_backend/_cython_configuration.py
packaging/pep517_backend/_transformers.py
packaging/pep517_backend/cli.py
packaging/pep517_backend/hooks.py
requirements/ci.txt
setup.cfg

Update mypy config to the strict typing we use on other projects

Strict typing

---

.github/workflows/ci-cd.yml

1.6.0 failed because the head_line could not be found https://github.com/aio-libs/frozenlist/actions/runs/14525098275/job/40755685776

Fix towncrier head_line missing the leading v

---

CHANGES/659.feature.rst
docs/spelling_wordlist.txt
frozenlist/_frozenlist.pyx
tests/test_frozenlist.py

Implements deepcopy support for FrozenList by adding a `__deepcopy__` method. This allows FrozenList objects to be deep copied using Python's `copy.deepcopy()` function, which was previously failing with a TypeError.
Users can now use `copy.deepcopy()` on FrozenList objects without errors. The deepcopy operation:
- Creates a complete copy of the FrozenList and all its contents
- Preserves the frozen state of the original list
- Correctly handles circular references and nested structures
- Maintains shared references within the copied structure
Closes #659
* The format is &lt;Name&gt; &lt;Surname&gt;.
* Please keep the list in alphabetical order, the file is sorted by name.
* name it `<issue_id>.<type>` for example (588.bugfix)
* if you don't have an `issue_id` change it to the pr id after …

Implement deepcopy support
